# Generated by Django 5.1 on 2024-09-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='57E11579F2F4', editable=False, max_length=12, unique=True),
        ),
    ]
