# Generated by Django 5.1 on 2024-09-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0007_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='BC637085D0FB', editable=False, max_length=12, unique=True),
        ),
    ]
