# Generated by Django 5.1 on 2024-09-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0008_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='E48B16D75A0E', editable=False, max_length=12, unique=True),
        ),
    ]
