# Generated by Django 5.1 on 2024-09-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0009_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='B48FCA4D44CD', editable=False, max_length=12, unique=True),
        ),
    ]
