# Generated by Django 5.1 on 2024-09-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0010_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='809375C2EFCD', editable=False, max_length=12, unique=True),
        ),
    ]
