# Generated by Django 5.1 on 2024-09-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0015_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='291AA97B53E9', editable=False, max_length=12, unique=True),
        ),
    ]
