# Generated by Django 5.1 on 2024-09-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0016_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='D997A40E7FF4', editable=False, max_length=12, unique=True),
        ),
    ]
