# Generated by Django 5.1 on 2024-09-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_email_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='062E33EA5FE9', editable=False, max_length=12, unique=True),
        ),
    ]
