# Generated by Django 5.1 on 2024-09-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='C5BC2E89BE16', editable=False, max_length=12, unique=True),
        ),
    ]
